AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: change email addresses
Resources:
  stkr:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: .
      Description: change email addresses
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::971579260814:role/service-role/stkr-role-k73ky253'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
      Tags:
        'lambda-console:blueprint': hello-world
